---
- name: Cloudblock - AWS ARM variant
  hosts: localhost
  gather_facts: true
  become: true
  tasks:

    - name: Custom facts
      ansible.builtin.set_fact:
        url_from_doh:
          adguard: https://dns.adguard.com/dns-query
          cloudflare: https://cloudflare-dns.com/dns-query
          cloudflare-security: https://security.cloudflare-dns.com/dns-query
          cloudflare-family: https://family.cloudflare-dns.com/dns-query
          applied-privacy: https://doh.applied-privacy.net/query
          google: https://dns.google/dns-query
          hurricane-electric: https://ordns.he.net/dns-query
          pi-dns: https://doh.pi-dns.com/dns-query
          quad9-recommended: https://dns.quad9.net/dns-query
          libre-dns: https://doh.libredns.gr/dns-query
          opendns: https://doh.opendns.com/dns-query

    - name: Docker apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Dpkg Architecture
      ansible.builtin.shell: |
        dpkg --print-architecture
      register: dpkg_arch

    - name: Docker apt repo
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Absent packages
      ansible.builtin.apt:
        pkg:
          - containerd
          - docker-compose
          - docker-doc
          - docker.io
          - podman-docker
          - runc
        state: absent

    - name: Required packages
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - libcap2-bin
          - python3-pip
          - ssl-cert
        state: latest
        update_cache: true

    - name: Docker packages
      ansible.builtin.apt:
        pkg:
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce
          - docker-ce-cli
        state: latest
        update_cache: true

    - name: Docker and boto python packages
      ansible.builtin.pip:
        name:
          - docker
          - boto
          - boto3
          - botocore
        executable: /usr/bin/pip3
        state: latest

    - name: IP Forwarding enable/persist
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: true
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf

    - name: Docker service started/enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Various container directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "999"
        group: "999"
        mode: '0750'
      with_items:
        - /opt/cloudflared
        - /opt/pihole
        - /opt/pihole/etc
        - /opt/pihole/dnsmasq.d
        - /opt/webproxy

    - name: Wireguard dir gets user ubuntu
      ansible.builtin.file:
        path: /opt/wireguard
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Secure proxy to pihole confs
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/opt/webproxy/{{ item }}"
        owner: root
        group: root
        mode: 0444
      with_items:
        - httpd-ssl.conf
        - httpd.conf

    - name: Cloudflared Dockerfile
      ansible.builtin.blockinfile:
        create: true
        mode: '0644'
        path: /opt/cloudflared/Dockerfile
        block: |
          FROM ubuntu:22.04
          EXPOSE 53/tcp
          EXPOSE 53/udp
          RUN apt-get update && \
              apt-get install -y wget && \
              wget https://github.com/cloudflare/cloudflared/releases/download/2020.10.2/cloudflared-linux-arm64 --directory-prefix=/usr/local/bin/ && \
              chmod 555 /usr/local/bin/cloudflared-linux-arm64
          ENTRYPOINT ["/usr/local/bin/cloudflared-linux-arm64", "proxy-dns","--address", "{{ docker_doh }}", "--port", "53", "--upstream", "{{ url_from_doh_provider[doh_provider] }}"]
      register: cloudflared_doh_dockerfile

    - name: Check cloudflared image exists
      community.docker.docker_image:
        name: cloudflared_doh
        state: present
        source: local
      register: cloudflared_image_check
      ignore_errors: true

    - name: Cloudflared image
      community.docker.docker_image:
        name: cloudflared_doh
        build:
          path: /opt/cloudflared
        source: build
        state: present
        force_source: "{{ cloudflared_doh_dockerfile.changed or cloudflared_image_check.failed }}"

    - name: Get SSM parameter ph_password
      ansible.builtin.set_fact:
        ph_password: "{{ lookup('aws_ssm', name_prefix + '-pihole-web-password', decrypt=True, region=aws_region) }}"
      no_log: true

# cloud + vpn = mtu restrictions that cause failures for sites like google.com or the play store
# a lower mtu fixes the problem
    - name: Cloudflared pihole and wireguard network
      community.docker.docker_network:
        name: cloudblock
        driver: bridge
        driver_options:
          com.docker.network.driver.mtu: 1380
        ipam_config:
          - subnet: "{{ docker_network }}/24"
            gateway: "{{ docker_gw }}"

    - name: Cloudflared_doh container
      community.docker.docker_container:
        name: cloudflared_doh
        image: cloudflared_doh
        networks:
          - name: cloudblock
            ipv4_address: "{{ docker_doh }}"
        restart_policy: "always"

    - name: Pihole container - without DNS listen
      community.docker.docker_container:
        name: pihole
        hostname: cloudblockpihole
        env:
          DNS1: 172.18.0.2
          DNS2: 172.18.0.2
          WEBPASSWORD: "{{ ph_password }}"
        image: pihole/pihole:latest
        networks:
          - name: cloudblock
            ipv4_address: "{{ docker_pihole }}"
        volumes:
          - /opt/pihole/etc:/etc/pihole/:rw
          - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
        restart_policy: "always"
      when: dns_novpn == "0"

    - name: Pihole container - with DNS listen
      community.docker.docker_container:
        name: pihole
        hostname: cloudblockpihole
        env:
          DNS1: 172.18.0.2
          DNS2: 172.18.0.2
          WEBPASSWORD: "{{ ph_password }}"
          DNSMASQ_USER: root
        image: pihole/pihole:latest
        networks:
          - name: cloudblock
            ipv4_address: "{{ docker_pihole }}"
        ports:
          - "53:53"
          - "53:53/udp"
        volumes:
          - /opt/pihole/etc:/etc/pihole/:rw
          - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
        restart_policy: "always"
      when: dns_novpn == "1"
      no_log: true

    - name: Wireguard container
      community.docker.docker_container:
        name: wireguard
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          SERVERURL: "auto"
          SERVERPORT: "51820"
          ALLOWEDIPS: "{% if vpn_traffic is not defined %}{{ docker_pihole }}/32,{{ docker_webproxy }}/32{% elif vpn_traffic == 'dns' %}{{ docker_pihole }}/32,{{ docker_webproxy }}/32{% elif vpn_traffic == 'peers' %}{{ docker_pihole }}/32,{{ docker_webproxy }}/32,{{ wireguard_network }}/24{% elif vpn_traffic == 'all' %}0.0.0.0/0{% else %}{{ docker_pihole }}/32,{{ docker_webproxy }}/32{% endif %}"
          PEERS: "{{ wireguard_peers }}"
          PEERDNS: "{{ docker_pihole }}"
          INTERNAL_SUBNET: "{{ wireguard_network }}"
        image: linuxserver/wireguard:latest
        networks:
          - name: cloudblock
            ipv4_address: "{{ docker_wireguard }}"
        ports:
          - "51820:51820/udp"
        sysctls:
          net.ipv4.conf.all.src_valid_mark: 1
        volumes:
          - /opt/wireguard:/config:rw
        restart_policy: "always"

    - name: Web proxy container for pihole
      community.docker.docker_container:
        name: web_proxy
        image: httpd:2.4
        networks:
          - name: cloudblock
            ipv4_address: "{{ docker_webproxy }}"
        ports:
          - "443:443"
        volumes:
          - /opt/webproxy/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
          - /opt/webproxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
          - /etc/ssl/certs/ssl-cert-snakeoil.pem:/usr/local/apache2/conf/server.crt:ro
          - /etc/ssl/private/ssl-cert-snakeoil.key:/usr/local/apache2/conf/server.key:ro
        restart_policy: "always"

    - name: Set peer count list
      ansible.builtin.set_fact:
        peer_count: "{{ range(1, wireguard_peers | int + 1) | list }}"

    - name: Wait for final peer conf (Wireguard)
      ansible.builtin.wait_for:
        path: "/opt/wireguard/peer{{ wireguard_peers }}/{{ item }}"
        state: present
        timeout: 600
        sleep: 1
      with_items:
        - "publickey-peer{{ wireguard_peers }}"
        - "privatekey-peer{{ wireguard_peers }}"
        - "peer{{ wireguard_peers }}.conf"
        - "peer{{ wireguard_peers }}.png"

    - name: instance id from metadata
      uri:
        url: http://169.254.169.254/latest/meta-data/instance-id
        return_content: yes
      register: instance_id_from_metadata

    - name: Upload peer confs to s3 (Wireguard) - publickey
      amazon.aws.aws_s3:
        mode: put
        bucket: "{{ s3_bucket }}"
        object: "wireguard/{{ instance_id_from_metadata.content }}/peer{{ item }}/publickey-peer{{ item }}"
        src: "/opt/wireguard/peer{{ item }}/publickey-peer{{ item }}"
        encrypt: yes
        encryption_mode: "aws:kms"
        encryption_kms_key_id: "{{ kms_key_id }}"
      with_items:
        - "{{ peer_count }}"

    - name: Upload peer confs to s3 (Wireguard) - privatekey
      amazon.aws.aws_s3:
        mode: put
        bucket: "{{ s3_bucket }}"
        object: "wireguard/{{ instance_id_from_metadata.content }}/peer{{ item }}/privatekey-peer{{ item }}"
        src: "/opt/wireguard/peer{{ item }}/privatekey-peer{{ item }}"
        encrypt: yes
        encryption_mode: "aws:kms"
        encryption_kms_key_id: "{{ kms_key_id }}"
      with_items:
        - "{{ peer_count }}"

    - name: Upload peer confs to s3 (Wireguard) - conf
      amazon.aws.aws_s3:
        mode: put
        bucket: "{{ s3_bucket }}"
        object: "wireguard/{{ instance_id_from_metadata.content }}/peer{{ item }}/peer{{ item }}.conf"
        src: "/opt/wireguard/peer{{ item }}/peer{{ item }}.conf"
        encrypt: yes
        encryption_mode: "aws:kms"
        encryption_kms_key_id: "{{ kms_key_id }}"
      with_items:
        - "{{ peer_count }}"

    - name: Upload peer confs to s3 (Wireguard) - png
      amazon.aws.aws_s3:
        mode: put
        bucket: "{{ s3_bucket }}"
        object: "wireguard/{{ instance_id_from_metadata.content }}/peer{{ item }}/peer{{ item }}.png"
        src: "/opt/wireguard/peer{{ item }}/peer{{ item }}.png"
        encrypt: yes
        encryption_mode: "aws:kms"
        encryption_kms_key_id: "{{ kms_key_id }}"
      with_items:
        - "{{ peer_count }}"
